2024-11-22 16:17:09.310 | INFO     | src.utils.logging_utils:wrapper:17 - Starting train
2024-11-22 16:17:10.282 | ERROR    | src.utils.logging_utils:wrapper:23 - Error in train: HTTP Error 404: The specified blob does not exist.
Traceback (most recent call last):

  File "/workspace/Torchscript-trainer/src/train.py", line 149, in <module>
    main()
    └ <function main at 0x7f90a7028680>

  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
    └ <function _run_hydra at 0x7f90b2348a40>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
    └ <function _run_app at 0x7f90b2348ae0>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
    └ <function run_and_report at 0x7f90b23489a0>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           └ <function _run_app.<locals>.<lambda> at 0x7f90a7028d60>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            │     └ <function Hydra.run at 0x7f90b2215c60>
            └ <hydra._internal.hydra.Hydra object at 0x7f90a798d220>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
          └ <function run_job at 0x7f90b22fb920>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
    │   │              │             └ {'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'paths': {'root_dir': '${...
    │   │              └ <function main at 0x7f90a70285e0>
    │   └ <property object at 0x7f90b232b380>
    └ JobReturn(overrides=[], cfg={'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 4...

  File "/workspace/Torchscript-trainer/src/train.py", line 141, in main
    train(cfg, trainer, model, datamodule)
    │     │    │        │      └ <src.datamodules.dogbreed_datamodule.DogBreedDataModule object at 0x7f90a6da8110>
    │     │    │        └ DogBreedClassifier(
    │     │    │            (model): ResNet(
    │     │    │              (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=Fal...
    │     │    └ <lightning.pytorch.trainer.trainer.Trainer object at 0x7f90a4204a70>
    │     └ {'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'paths': {'root_dir': '${...
    └ <function train at 0x7f90a7028360>

> File "/workspace/Torchscript-trainer/src/utils/logging_utils.py", line 19, in wrapper
    result = func(*args, **kwargs)
             │     │       └ {}
             │     └ ({'task_name': 'train', 'tags': ['dev'], 'train': True, 'test': True, 'ckpt_path': None, 'seed': 42, 'paths': {'root_dir': '$...
             └ <function train at 0x7f90a70282c0>

  File "/workspace/Torchscript-trainer/src/train.py", line 63, in train
    trainer.fit(model, datamodule)
    │       │   │      └ <src.datamodules.dogbreed_datamodule.DogBreedDataModule object at 0x7f90a6da8110>
    │       │   └ DogBreedClassifier(
    │       │       (model): ResNet(
    │       │         (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=Fal...
    │       └ <function Trainer.fit at 0x7f90a714ad40>
    └ <lightning.pytorch.trainer.trainer.Trainer object at 0x7f90a4204a70>

  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
    │    └ <function _call_and_handle_interrupt at 0x7f90a72419e0>
    └ <module 'lightning.pytorch.trainer.call' from '/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/py...
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           │           │       └ {}
           │           └ (DogBreedClassifier(
           │               (model): ResNet(
           │                 (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=Fa...
           └ <bound method Trainer._fit_impl of <lightning.pytorch.trainer.trainer.Trainer object at 0x7f90a4204a70>>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
    │    │    │                └ None
    │    │    └ DogBreedClassifier(
    │    │        (model): ResNet(
    │    │          (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=Fal...
    │    └ <function Trainer._run at 0x7f90a714b4c0>
    └ <lightning.pytorch.trainer.trainer.Trainer object at 0x7f90a4204a70>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 941, in _run
    self._data_connector.prepare_data()
    │    │               └ <function _DataConnector.prepare_data at 0x7f90a70dc680>
    │    └ <lightning.pytorch.trainer.connectors.data_connector._DataConnector object at 0x7f90a42a1ac0>
    └ <lightning.pytorch.trainer.trainer.Trainer object at 0x7f90a4204a70>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 93, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
    │    │                               └ <lightning.pytorch.trainer.trainer.Trainer object at 0x7f90a4204a70>
    │    └ <function _call_lightning_datamodule_hook at 0x7f90a7264540>
    └ <module 'lightning.pytorch.trainer.call' from '/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/py...
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 189, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           │   │       └ {}
           │   └ ()
           └ <bound method DogBreedDataModule.prepare_data of <src.datamodules.dogbreed_datamodule.DogBreedDataModule object at 0x7f90a6da...

  File "/workspace/Torchscript-trainer/src/datamodules/dogbreed_datamodule.py", line 38, in prepare_data
    download_and_extract_archive(
    └ <function download_and_extract_archive at 0x7f90a6593ba0>

  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/torchvision/datasets/utils.py", line 395, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
    │            │    │              │         └ None
    │            │    │              └ 'dogbreed_data.zip'
    │            │    └ '/workspace/Torchscript-trainer/data/dogbreed'
    │            └ 'https://sensitivedatashareblob.blob.core.windows.net/files/dogbreed_data.zip'
    └ <function download_url at 0x7f90a6593600>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/torchvision/datasets/utils.py", line 122, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
          │                 │             └ 3
          │                 └ 'https://sensitivedatashareblob.blob.core.windows.net/files/dogbreed_data.zip'
          └ <function _get_redirect_url at 0x7f90a6593560>
  File "/workspace/Torchscript-trainer/.venv/lib/python3.12/site-packages/torchvision/datasets/utils.py", line 66, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
         │      │       │       │      │       │       │            └ {'Method': 'HEAD', 'User-Agent': 'pytorch/vision'}
         │      │       │       │      │       │       └ 'https://sensitivedatashareblob.blob.core.windows.net/files/dogbreed_data.zip'
         │      │       │       │      │       └ <class 'urllib.request.Request'>
         │      │       │       │      └ <module 'urllib.request' from '/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py'>
         │      │       │       └ <module 'urllib' from '/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/__init__.py'>
         │      │       └ <function urlopen at 0x7f90b3b714e0>
         │      └ <module 'urllib.request' from '/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py'>
         └ <module 'urllib' from '/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/__init__.py'>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           │      │    │    │     └ <object object at 0x7f918b828c40>
           │      │    │    └ None
           │      │    └ <urllib.request.Request object at 0x7f90a48f4830>
           │      └ <function OpenerDirector.open at 0x7f90b38be980>
           └ <urllib.request.OpenerDirector object at 0x7f90a42a0b90>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               │    │    └ <http.client.HTTPResponse object at 0x7f90a5ba1ae0>
               │    └ <urllib.request.Request object at 0x7f90a48f4830>
               └ <bound method HTTPErrorProcessor.http_response of <urllib.request.HTTPErrorProcessor object at 0x7f90a48f57c0>>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               │    │      └ <function OpenerDirector.error at 0x7f90b38beac0>
               │    └ <urllib.request.OpenerDirector object at 0x7f90a42a0b90>
               └ <urllib.request.HTTPErrorProcessor object at 0x7f90a48f57c0>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           │    │            └ ({'default': [<urllib.request.HTTPDefaultErrorHandler object at 0x7f90a42a0dd0>], 301: [<urllib.request.HTTPRedirectHandler o...
           │    └ <function OpenerDirector._call_chain at 0x7f90b38be8e0>
           └ <urllib.request.OpenerDirector object at 0x7f90a42a0b90>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             │     └ (<urllib.request.Request object at 0x7f90a48f4830>, <http.client.HTTPResponse object at 0x7f90a5ba1ae0>, 404, 'The specified ...
             └ <bound method HTTPDefaultErrorHandler.http_error_default of <urllib.request.HTTPDefaultErrorHandler object at 0x7f90a42a0dd0>>
  File "/home/gitpod/.pyenv/versions/3.12.6/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
          │         │   │         │     │    │     └ <http.client.HTTPResponse object at 0x7f90a5ba1ae0>
          │         │   │         │     │    └ <http.client.HTTPMessage object at 0x7f90a42a1400>
          │         │   │         │     └ 'The specified blob does not exist.'
          │         │   │         └ 404
          │         │   └ <property object at 0x7f90b3b57bf0>
          │         └ <urllib.request.Request object at 0x7f90a48f4830>
          └ <class 'urllib.error.HTTPError'>

urllib.error.HTTPError: HTTP Error 404: The specified blob does not exist.
2024-11-22 16:39:51.726 | INFO     | src.utils.logging_utils:wrapper:17 - Starting train
2024-11-22 16:42:01.853 | INFO     | src.utils.logging_utils:wrapper:20 - Finished train
2024-11-22 16:42:01.853 | INFO     | src.utils.logging_utils:wrapper:17 - Starting test
2024-11-22 16:42:04.214 | INFO     | src.utils.logging_utils:wrapper:20 - Finished test
